Wrap all urllib3 read ProtocolErrors as GitProtocolError
jelmer/dulwich pull request #1261
Opened 2024-03-05 19:35 UTC by nanonyme

Fixes https://github.com/jelmer/dulwich/issues/1225

2024-03-05 19:41 UTC, nanonyme commented
@jelmer not sure if this is overkill. It seemed simpler to just add an exception to protocol.py but that would have leaked HTTP client implementation details there (it looked like this has been insulated into client.py).

2024-03-13 18:04 UTC, jelmer requested changes
Looks good to me overall, just one nit about the function name.

2024-03-13 18:04 UTC, jelmer commented on dulwich/client.py
> +def wrap_exceptions(func):
This should probably be private and include urllib3 in the name.

2024-03-13 20:38 UTC, nanonyme commented
Looks like CI is failing all over due to ruff

2024-03-14 17:12 UTC, jelmer approved these changes

2024-03-14 17:12 UTC, merged

2024-03-14 17:55 UTC, nanonyme commented
Is there any plan for next release?

2024-03-15 21:12 UTC, jelmer commented
Not currently but I can probably do one in the next couple of weeks