Support Python 3.13
jelmer/dulwich pull request #1353
Opened 2024-08-06 22:45 UTC by edgarrmondragon

2024-08-06 22:48 UTC, jelmer commented
You'll also need to update python-distributions.yml - that's where the actual wheels are built and uploaded

2024-08-06 22:48 UTC, jelmer requested changes
You'll also need to update python-distributions.yml - that's where the actual wheels are built and uploaded

2024-08-07 01:43 UTC, jelmer approved these changes

2024-08-07 01:46 UTC, edgarrmondragon commented
I think the error is in the 3.13 workflow is https://github.com/python/cpython/issues/122728. The `3.13.0rc2` release will probably be alright.

2024-08-07 02:06 UTC, merged